### ISSUE TITLE
Character sheet is still not finished

### ISSUE THREAD

**Issue by gitkrax** [gitkrax/epshoe#10]
Character sheet needs more work. It lacks room for equipment and health & stability should be easier to track.

**Todo**
- [X] health & stability (fixed in c674fedd43ff760c7be652407568a3ea34d4c703)
- [X] equipment box as a large text-area (fixed in c674fedd43ff760c7be652407568a3ea34d4c703)
- [ ] stealth modifier

**Comment by ScottMaclure** [comment]
Rather than equpment being 3 distinct "rows" - how about a large textarea style box?

**Comment by ScottMaclure** [comment]
Q) Place for "Stealth Modifier" (I guess I'd note that in the "Morph" input)?

**Comment by gitkrax** [comment]
Hey, Scott. Sounds good. I think I'll try to get in a couple more sessions of playtest before making changes, so I can implement all of them at the same time. If you happen to have the chance, you can try to take a crack at modifying the character sheet, it's in the repo.

**Comment by gitkrax** [comment]
Closing this for now. The character sheet is far from perfect, but I'll open more issues as more ideas come up. A complete redesign is probably a good idea at some point anyway.

Player characters don't have stealth modifiers, so there is no need to include that in the character sheet.
